spring.application.name=application-tracker

spring.datasource.url=jdbc:mysql://localhost:3306/apdb
spring.datasource.username=root
spring.datasource.password=akhil@2002


spring.jpa.hibernate.ddl-auto=create
